### PR TITLE
Fix rosdep

### PR DESCRIPTION
**Pull request by peci1**

### CODE REVIEW

**Comment by matemat13** [comment]
why is this a problem?

**Comment by peci1** [comment]
With this change, the whole package can be installed via standard ways (`rosdep install`) without calling the custom install script. If the dependencies are not in package.xml, rosdep cannot know it should install them.

**Comment by matemat13** [comment]
That's a nice feature, but even with your patch I'm still getting an error after calling `rosdep install ouster_ros`:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ouster_ros: Cannot locate rosdep definition for [mrs_msgs]
```
even thought the output of `rospack list | grep mrs_msgs` is
```
mrs_msgs /home/matous/mrs_workspace/src/uav_core/ros_packages/mrs_msgs
```
so ROS knows about the `mrs_msgs` package... It seems that other stuff is broken as well :D Any ideas?

**Comment by peci1** [comment]
Yes, I didn't write the full rosdep command... what should usually used is

    rosdep install --from-paths src --ignore-src -r

The --ignore-src should solve the error you're seeing.

**Comment by matemat13** [comment]
thanks for the fix, since I've been at it, I've also fixed the `eigen` dependency in `package.xml` :)

**Pull request merged**
