### PR TITLE
Getting diagnostic alerts from the lidar during run

### PR DESCRIPTION
**Pull request by pritzvac**
- Printing a warning when the client poll to the lidar device timeouts (e.g. when it physically disconnects)
- Obtaining diagnostic alerts from the lidar at the rate of 1 Hz, publishing them to rostopic, printing all currently active alerts to rosconsole, and printing a warning if an ERROR or SHOT_LIMITING appears in the alerts history
- Added `pixels_per_column`, `columns_per_frame` and `pixel_shift_by_row` to the OusterInfo message

### CODE REVIEW

**Comment by matemat13** [comment]
Looks great! This should definitely be integrated with [uav_status](https://github.com/ctu-mrs/mrs_uav_status) so that the user can clearly see when Ouster is misbehaving for some reason or even disconnected! @DanHert how hard would that be?

Regarding `pixels_per_column`, `columns_per_frame` and `pixel_shift_by_row` - is this needed in the new firmwares? The LUT table can be constructed even without this information just from the beam angle arrays, no? I'm not opposing the addition, just curious about what you're using it for.

**Comment by pritzvac** [comment]
Good idea, I guess we can just publish the active alerts as a message to uav_status. When ouster behaves normally, there should be no alerts produced.

I'm not sure if these fields are necessary. I added them after I tried running uav_detect on a rosbag and was missing these data to properly initialize the LUT (although afterwards I switched to just loading the data from the json metadata file). But when I'm looking at the sensor_info message from some rosbag, the `beam_azimuth_angles` array seems to be equally long as `beam_altitude_angles` and contains just angles between 11.2 and -11.11. And the method for LUT creation requires width and height of the scan as well as the arrays: https://github.com/ctu-mrs/ouster/blob/d0432b77c8c74732983a77b853ac8ed01e7693d0/ouster_client/src/lidar_scan.cpp#L11 So I guess it's required but I don't know if it's any different with newer firmwares.

**Comment by matemat13** [comment]
let's merge this?

**Comment by pritzvac** [comment]
Yes, I'll merge it. I just tested on a real ouster that it works correctly.

**Pull request merged**
